name: SBOM Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sbom_scan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#Генерація SBOM через Syft
      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          image: bkimminich/juice-shop
          format: cyclonedx-json
          output: sbom.json

#Перевірка з Grype
      - name: Scan SBOM for vulnerabilities with Grype
        uses: anchore/scan-action@v5
        with:
          sbom: sbom.json
