name: SBOM Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  security-events: write
  contents: read

jobs:
  sbom_scan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Create SBOM - Syft
      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          image: bkimminich/juice-shop
          format: cyclonedx-json
          output-file: sbom.json

      # Check with Grype (using scan-action v6)
      - name: Scan SBOM for vulnerabilities with Grype
        id: scan  # Add ID for output reference (optional but recommended)
        uses: anchore/scan-action@v6
        with:
          sbom: sbom.json
          severity-cutoff: high
          output-format: sarif
          output: grype-results.sarif
          fail-build: false

      # Report to Security tab
      - name: Upload vulnerability report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: grype-results.sarif  # Or use ${{ steps.scan.outputs.sarif }} if you prefer dynamic reference
