name: SBOM Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  sbom_scan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          image: bkimminich/juice-shop
          format: cyclonedx-json
          output-file: sbom.json

      - name: Scan SBOM for vulnerabilities with Grype
        id: scan
        uses: anchore/scan-action@v6
        with:
          sbom: sbom.json
          output-format: sarif
          output: grype-results.sarif
          fail-build: false

      - name: Upload vulnerability report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./grype-results.sarif
